/// Authentication
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_CONFIRM_ACCOUNT = "USER_CONFIRM_ACCOUNT";
export const CANCEL_ERROR = "CANCEL_ERROR";
export const ERROR = "ERROR";
export const SUCCESS = "SUCCESS";
export const REDIRECT = "REDIRECT";

// Cart
export const GET_CART = "GET_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CREATE_ORDER = "CREATE_ORDER";
export const CLEAR_ORDER = "CLEAR_ORDER";
export const CLEAR_CART = "CLEAR_CART";

// Products
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_TYPE = "FILTER_PRODUCTS_BY_SIZE";
export const FILTER_PRODUCTS_BY_CATEGORY = "FILTER_PRODUCTS_BY_CATEGORY";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

// Places
export const PLACES_REQUEST = "PLACES_REQUEST";
export const GET_PLACES = "GET_PLACES";
export const ADD_PLACE_REQUEST = "ADD_PLACE_REQUEST";
export const ADD_PLACE = "ADD_PLACE";
export const EDIT_PLACE_REQUEST = "EDIT_PLACE_REQUEST";
export const EDIT_PLACE = "EDIT_PLACE";
export const DELETE_PLACE_REQUEST = "DELETE_PLACE_REQUEST";
export const DELETE_PLACE = "DELETE_PLACE";

// Single Place
export const GET_PLACE_REQUEST = "PLACE_REQUEST";
export const GET_PLACE = "GET_PLACE";

// Categories
export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const EDIT_CATEGORY_REQUEST = "EDIT_CATEGORY_REQUEST";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY = "ADD_CATEGORY";

// Types
export const TYPES_REQUEST = "TYPES_REQUEST";
export const GET_TYPES = "GET_TYPES";
export const FILTER_TYPES_BY_CATEGORY = "FILTER_TYPES_BY_CATEGORY";
export const ADD_TYPE_REQUEST = "ADD_TYPE_REQUEST";
export const ADD_TYPE = "ADD_TYPE";
export const EDIT_TYPE_REQUEST = "EDIT_TYPE_REQUEST";
export const EDIT_TYPE = "EDIT_TYPE";
export const DELETE_TYPE_REQUEST = "DELETE_TYPE_REQUEST";
export const DELETE_TYPE = "DELETE_TYPE";

// Places Client
export const PLACES_REQUEST_BY_CLIENT = "PLACES_REQUEST_BY_CLIENT";
export const GET_PLACES_BY_CLIENT = "GET_PLACES_BY_CLIENT";


// Orders
export const GET_ORDERS = "GET_ORDERS";